CREATE TABLE IF NOT EXISTS guilds (
    guild_id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    icon_url TEXT,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS admin_users (
    discord_user_id TEXT PRIMARY KEY,
    role TEXT NOT NULL CHECK (role IN ('global_admin', 'viewer')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS guild_permissions (
    guild_id TEXT NOT NULL REFERENCES guilds(guild_id) ON DELETE CASCADE,
    discord_user_id TEXT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('guild_admin', 'editor', 'viewer')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (guild_id, discord_user_id)
);

CREATE TABLE IF NOT EXISTS feature_flags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id TEXT NOT NULL REFERENCES guilds(guild_id) ON DELETE CASCADE,
    feature_key TEXT NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT FALSE,
    updated_by_discord_user_id TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (guild_id, feature_key)
);

CREATE TABLE IF NOT EXISTS mention_reactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id TEXT NOT NULL REFERENCES guilds(guild_id) ON DELETE CASCADE,
    reaction_key TEXT NOT NULL,
    keyword TEXT NOT NULL,
    match_type TEXT NOT NULL DEFAULT 'contains' CHECK (match_type IN ('contains', 'exact', 'regex')),
    reaction_kind TEXT NOT NULL CHECK (reaction_kind IN ('random', 'search')),
    name TEXT NOT NULL,
    description TEXT,
    admin_only BOOLEAN NOT NULL DEFAULT FALSE,
    is_system BOOLEAN NOT NULL DEFAULT FALSE,
    is_deletable BOOLEAN NOT NULL DEFAULT TRUE,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (guild_id, reaction_key),
    UNIQUE (guild_id, keyword)
);

CREATE TABLE IF NOT EXISTS mention_reaction_choices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id TEXT NOT NULL REFERENCES guilds(guild_id) ON DELETE CASCADE,
    mention_reaction_id BIGINT NOT NULL REFERENCES mention_reactions(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    body TEXT,
    image_path TEXT,
    appearance_rate INTEGER NOT NULL DEFAULT 1 CHECK (appearance_rate > 0),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK (body IS NOT NULL OR image_path IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS mention_search_handlers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id TEXT NOT NULL REFERENCES guilds(guild_id) ON DELETE CASCADE,
    mention_reaction_id BIGINT NOT NULL REFERENCES mention_reactions(id) ON DELETE CASCADE,
    handler_key TEXT NOT NULL,
    settings_json JSONB NOT NULL DEFAULT '{}'::JSONB,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (guild_id, handler_key),
    UNIQUE (mention_reaction_id)
);

CREATE TABLE IF NOT EXISTS reactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id TEXT NOT NULL REFERENCES guilds(guild_id) ON DELETE CASCADE,
    trigger_text TEXT NOT NULL,
    response_text TEXT,
    image_path TEXT,
    emoji_internal TEXT,
    match_type TEXT NOT NULL DEFAULT 'contains' CHECK (match_type IN ('contains', 'exact', 'regex')),
    priority INTEGER NOT NULL DEFAULT 0,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK (response_text IS NOT NULL OR image_path IS NOT NULL OR emoji_internal IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS ng_words (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id TEXT NOT NULL REFERENCES guilds(guild_id) ON DELETE CASCADE,
    word TEXT NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (guild_id, word)
);

CREATE TABLE IF NOT EXISTS special_effect_tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id TEXT NOT NULL REFERENCES guilds(guild_id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    description TEXT,
    color TEXT,
    admin_only BOOLEAN NOT NULL DEFAULT FALSE,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    is_deletable BOOLEAN NOT NULL DEFAULT TRUE,
    priority INTEGER NOT NULL DEFAULT 0,
    effect_type TEXT NOT NULL CHECK (
        effect_type IN (
            'probability_multiplier',
            'next_action_count_add',
            'count_add',
            'mode_lottery',
            'pseudo_offline_lottery',
            'mini_ichiyon',
            'shikocchi_lottery',
            'custom'
        )
    ),
    effect_config_json JSONB NOT NULL DEFAULT '{}'::JSONB,
    additional_text TEXT,
    additional_post_timing TEXT NOT NULL DEFAULT 'after_response'
        CHECK (additional_post_timing IN ('none', 'before_response', 'after_response')),
    expires_at TIMESTAMPTZ,
    cooldown_seconds INTEGER CHECK (cooldown_seconds IS NULL OR cooldown_seconds >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (guild_id, name)
);

CREATE TABLE IF NOT EXISTS special_effect_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id TEXT NOT NULL REFERENCES guilds(guild_id) ON DELETE CASCADE,
    special_effect_tag_id BIGINT NOT NULL REFERENCES special_effect_tags(id) ON DELETE CASCADE,
    target_type TEXT NOT NULL CHECK (target_type IN ('mention_reaction_choice', 'reaction', 'ng_word')),
    target_id BIGINT NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (special_effect_tag_id, target_type, target_id)
);

CREATE TABLE IF NOT EXISTS counters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id TEXT NOT NULL REFERENCES guilds(guild_id) ON DELETE CASCADE,
    count_key TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    initial_value INTEGER NOT NULL DEFAULT 0,
    reset_type TEXT NOT NULL DEFAULT 'none'
        CHECK (reset_type IN ('none', 'daily', 'monthly', 'monthly_day', 'manual')),
    reset_day INTEGER CHECK (reset_day IS NULL OR (reset_day >= 1 AND reset_day <= 31)),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (guild_id, count_key)
);

CREATE TABLE IF NOT EXISTS counter_states (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id TEXT NOT NULL REFERENCES guilds(guild_id) ON DELETE CASCADE,
    counter_id BIGINT NOT NULL REFERENCES counters(id) ON DELETE CASCADE,
    current_value INTEGER NOT NULL DEFAULT 0,
    period_key TEXT,
    last_reset_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (guild_id, counter_id)
);

CREATE TABLE IF NOT EXISTS modes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id TEXT NOT NULL REFERENCES guilds(guild_id) ON DELETE CASCADE,
    mode_key TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    behavior_type TEXT NOT NULL CHECK (behavior_type IN ('reply', 'offline')),
    duration_seconds INTEGER CHECK (duration_seconds IS NULL OR duration_seconds > 0),
    mode_icon_path TEXT,
    enter_message TEXT,
    exit_message TEXT,
    enter_gif_path TEXT,
    exit_gif_path TEXT,
    enter_notify_channel_id TEXT,
    exit_notify_channel_id TEXT,
    reaction_channel_ids JSONB NOT NULL DEFAULT '[]'::JSONB,
    ignore_channel_ids JSONB NOT NULL DEFAULT '[]'::JSONB,
    cooldown_config_json JSONB NOT NULL DEFAULT '{}'::JSONB,
    appearance_config_json JSONB NOT NULL DEFAULT '{}'::JSONB,
    enabled BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (guild_id, mode_key)
);

CREATE TABLE IF NOT EXISTS mode_reply_choices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id TEXT NOT NULL REFERENCES guilds(guild_id) ON DELETE CASCADE,
    mode_id BIGINT NOT NULL REFERENCES modes(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    body TEXT,
    image_path TEXT,
    appearance_rate INTEGER NOT NULL DEFAULT 1 CHECK (appearance_rate > 0),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK (body IS NOT NULL OR image_path IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS mode_trigger_conditions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id TEXT NOT NULL REFERENCES guilds(guild_id) ON DELETE CASCADE,
    mode_id BIGINT NOT NULL REFERENCES modes(id) ON DELETE CASCADE,
    condition_group_key TEXT NOT NULL DEFAULT 'default',
    group_operator TEXT NOT NULL DEFAULT 'AND' CHECK (group_operator IN ('AND', 'OR')),
    condition_type TEXT NOT NULL CHECK (
        condition_type IN (
            'probability',
            'counter_threshold',
            'period_not_triggered',
            'manual',
            'test',
            'schedule'
        )
    ),
    condition_config_json JSONB NOT NULL DEFAULT '{}'::JSONB,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS mode_exit_conditions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id TEXT NOT NULL REFERENCES guilds(guild_id) ON DELETE CASCADE,
    mode_id BIGINT NOT NULL REFERENCES modes(id) ON DELETE CASCADE,
    condition_type TEXT NOT NULL CHECK (condition_type IN ('duration_elapsed', 'manual')),
    condition_config_json JSONB NOT NULL DEFAULT '{}'::JSONB,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS mode_states (
    guild_id TEXT PRIMARY KEY REFERENCES guilds(guild_id) ON DELETE CASCADE,
    current_mode_id BIGINT REFERENCES modes(id) ON DELETE SET NULL,
    active_until TIMESTAMPTZ,
    pseudo_offline_until TIMESTAMPTZ,
    shikocchi_count INTEGER NOT NULL DEFAULT 0 CHECK (shikocchi_count >= 0),
    period_states_json JSONB NOT NULL DEFAULT '{}'::JSONB,
    state_json JSONB NOT NULL DEFAULT '{}'::JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS auto_posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id TEXT NOT NULL REFERENCES guilds(guild_id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    body TEXT,
    image_path TEXT,
    channel_id TEXT,
    schedule_type TEXT NOT NULL,
    schedule_value TEXT NOT NULL,
    repeat_rule TEXT,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    last_posted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS deck_settings (
    guild_id TEXT PRIMARY KEY REFERENCES guilds(guild_id) ON DELETE CASCADE,
    allowed_channel_ids JSONB NOT NULL DEFAULT '[]'::JSONB,
    result_limit INTEGER NOT NULL DEFAULT 2 CHECK (result_limit > 0),
    default_format_policy TEXT NOT NULL DEFAULT 'latest',
    forbidden_channel_message TEXT,
    enabled BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_guild_permissions_discord_user_id
    ON guild_permissions(discord_user_id);

CREATE INDEX IF NOT EXISTS idx_feature_flags_guild_id
    ON feature_flags(guild_id);

CREATE INDEX IF NOT EXISTS idx_mention_reactions_guild_id_enabled
    ON mention_reactions(guild_id, enabled);

CREATE INDEX IF NOT EXISTS idx_mention_reactions_keyword_length
    ON mention_reactions(guild_id, LENGTH(keyword) DESC, created_at ASC);

CREATE INDEX IF NOT EXISTS idx_mention_reaction_choices_reaction_id
    ON mention_reaction_choices(mention_reaction_id);

CREATE INDEX IF NOT EXISTS idx_mention_search_handlers_reaction_id
    ON mention_search_handlers(mention_reaction_id);

CREATE INDEX IF NOT EXISTS idx_reactions_guild_id_enabled_priority
    ON reactions(guild_id, enabled, priority DESC);

CREATE INDEX IF NOT EXISTS idx_ng_words_guild_id
    ON ng_words(guild_id);

CREATE INDEX IF NOT EXISTS idx_special_effect_tags_guild_id
    ON special_effect_tags(guild_id);

CREATE INDEX IF NOT EXISTS idx_special_effect_assignments_target
    ON special_effect_assignments(guild_id, target_type, target_id);

CREATE INDEX IF NOT EXISTS idx_counters_guild_id
    ON counters(guild_id);

CREATE INDEX IF NOT EXISTS idx_counter_states_counter_id
    ON counter_states(counter_id);

CREATE INDEX IF NOT EXISTS idx_modes_guild_id
    ON modes(guild_id);

CREATE INDEX IF NOT EXISTS idx_mode_reply_choices_mode_id
    ON mode_reply_choices(mode_id);

CREATE INDEX IF NOT EXISTS idx_mode_trigger_conditions_mode_id
    ON mode_trigger_conditions(mode_id);

CREATE INDEX IF NOT EXISTS idx_mode_exit_conditions_mode_id
    ON mode_exit_conditions(mode_id);

CREATE INDEX IF NOT EXISTS idx_auto_posts_guild_id_enabled
    ON auto_posts(guild_id, enabled);
