CREATE TABLE IF NOT EXISTS guilds (
    guild_id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS admin_users (
    discord_user_id TEXT PRIMARY KEY,
    role TEXT NOT NULL CHECK (role IN ('global_admin', 'viewer')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS guild_permissions (
    guild_id TEXT NOT NULL REFERENCES guilds(guild_id) ON DELETE CASCADE,
    discord_user_id TEXT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('guild_admin', 'editor', 'viewer')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (guild_id, discord_user_id)
);

CREATE TABLE IF NOT EXISTS feature_flags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id TEXT NOT NULL REFERENCES guilds(guild_id) ON DELETE CASCADE,
    feature_key TEXT NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT FALSE,
    updated_by_discord_user_id TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (guild_id, feature_key)
);

CREATE TABLE IF NOT EXISTS quotes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id TEXT NOT NULL REFERENCES guilds(guild_id) ON DELETE CASCADE,
    text TEXT,
    image_path TEXT,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK (text IS NOT NULL OR image_path IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS kuji_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id TEXT NOT NULL REFERENCES guilds(guild_id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    body TEXT,
    image_path TEXT,
    appearance_rate INTEGER NOT NULL DEFAULT 1 CHECK (appearance_rate > 0),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS reactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id TEXT NOT NULL REFERENCES guilds(guild_id) ON DELETE CASCADE,
    trigger_text TEXT NOT NULL,
    response_text TEXT,
    image_path TEXT,
    emoji_internal TEXT,
    match_type TEXT NOT NULL DEFAULT 'contains' CHECK (match_type IN ('contains', 'exact', 'regex')),
    priority INTEGER NOT NULL DEFAULT 0,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK (response_text IS NOT NULL OR image_path IS NOT NULL OR emoji_internal IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS ng_words (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id TEXT NOT NULL REFERENCES guilds(guild_id) ON DELETE CASCADE,
    word TEXT NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (guild_id, word)
);

CREATE TABLE IF NOT EXISTS auto_posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id TEXT NOT NULL REFERENCES guilds(guild_id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    body TEXT,
    image_path TEXT,
    channel_id TEXT,
    schedule_type TEXT NOT NULL,
    schedule_value TEXT NOT NULL,
    repeat_rule TEXT,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    last_posted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS modes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id TEXT NOT NULL REFERENCES guilds(guild_id) ON DELETE CASCADE,
    mode_key TEXT NOT NULL,
    display_name TEXT NOT NULL,
    activation_type TEXT NOT NULL CHECK (activation_type IN ('probability', 'count_threshold', 'manual')),
    duration_seconds INTEGER NOT NULL DEFAULT 180 CHECK (duration_seconds > 0),
    notify_channel_id TEXT,
    reaction_channel_ids JSONB NOT NULL DEFAULT '[]'::JSONB,
    ignore_channel_ids JSONB NOT NULL DEFAULT '[]'::JSONB,
    enabled BOOLEAN NOT NULL DEFAULT FALSE,
    settings JSONB NOT NULL DEFAULT '{}'::JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (guild_id, mode_key)
);

CREATE TABLE IF NOT EXISTS mode_states (
    guild_id TEXT PRIMARY KEY REFERENCES guilds(guild_id) ON DELETE CASCADE,
    current_mode_key TEXT,
    active_until TIMESTAMPTZ,
    pseudo_offline_until TIMESTAMPTZ,
    narita_count INTEGER NOT NULL DEFAULT 0 CHECK (narita_count >= 0),
    narita_period_key TEXT,
    narita_activated_in_period BOOLEAN NOT NULL DEFAULT FALSE,
    state JSONB NOT NULL DEFAULT '{}'::JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS special_effect_tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id TEXT NOT NULL REFERENCES guilds(guild_id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    effect_type TEXT NOT NULL CHECK (
        effect_type IN (
            'probability_multiplier',
            'next_action_count_add',
            'count_add',
            'mode_lottery',
            'pseudo_offline_lottery'
        )
    ),
    effect_value JSONB NOT NULL DEFAULT '{}'::JSONB,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (guild_id, name)
);

CREATE TABLE IF NOT EXISTS reaction_special_effect_tags (
    reaction_id BIGINT NOT NULL REFERENCES reactions(id) ON DELETE CASCADE,
    special_effect_tag_id BIGINT NOT NULL REFERENCES special_effect_tags(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (reaction_id, special_effect_tag_id)
);

CREATE TABLE IF NOT EXISTS deck_settings (
    guild_id TEXT PRIMARY KEY REFERENCES guilds(guild_id) ON DELETE CASCADE,
    allowed_channel_ids JSONB NOT NULL DEFAULT '[]'::JSONB,
    result_limit INTEGER NOT NULL DEFAULT 2 CHECK (result_limit > 0),
    default_format_policy TEXT NOT NULL DEFAULT 'latest',
    forbidden_channel_message TEXT,
    enabled BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_guild_permissions_discord_user_id
    ON guild_permissions(discord_user_id);

CREATE INDEX IF NOT EXISTS idx_feature_flags_guild_id
    ON feature_flags(guild_id);

CREATE INDEX IF NOT EXISTS idx_quotes_guild_id
    ON quotes(guild_id);

CREATE INDEX IF NOT EXISTS idx_kuji_results_guild_id
    ON kuji_results(guild_id);

CREATE INDEX IF NOT EXISTS idx_reactions_guild_id_enabled_priority
    ON reactions(guild_id, enabled, priority DESC);

CREATE INDEX IF NOT EXISTS idx_ng_words_guild_id
    ON ng_words(guild_id);

CREATE INDEX IF NOT EXISTS idx_auto_posts_guild_id_enabled
    ON auto_posts(guild_id, enabled);

CREATE INDEX IF NOT EXISTS idx_modes_guild_id
    ON modes(guild_id);

CREATE INDEX IF NOT EXISTS idx_special_effect_tags_guild_id
    ON special_effect_tags(guild_id);
