CREATE TABLE IF NOT EXISTS counters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id TEXT NOT NULL REFERENCES guilds(guild_id) ON DELETE CASCADE,
    count_key TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    initial_value INTEGER NOT NULL DEFAULT 0,
    reset_type TEXT NOT NULL DEFAULT 'none',
    reset_day INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (guild_id, count_key)
);

CREATE TABLE IF NOT EXISTS counter_states (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id TEXT NOT NULL REFERENCES guilds(guild_id) ON DELETE CASCADE,
    counter_id BIGINT NOT NULL REFERENCES counters(id) ON DELETE CASCADE,
    current_value INTEGER NOT NULL DEFAULT 0,
    last_reset_at TIMESTAMPTZ,
    state_json JSONB NOT NULL DEFAULT '{}'::JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (guild_id, counter_id)
);

CREATE TABLE IF NOT EXISTS modes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id TEXT NOT NULL REFERENCES guilds(guild_id) ON DELETE CASCADE,
    mode_key TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    behavior_type TEXT NOT NULL DEFAULT 'reply',
    duration_seconds INTEGER,
    mode_icon_path TEXT,
    enter_message TEXT,
    exit_message TEXT,
    enter_gif_path TEXT,
    exit_gif_path TEXT,
    enter_notify_channel_id TEXT,
    exit_notify_channel_id TEXT,
    reaction_channel_ids JSONB NOT NULL DEFAULT '[]'::JSONB,
    ignore_channel_ids JSONB NOT NULL DEFAULT '[]'::JSONB,
    cooldown_config_json JSONB NOT NULL DEFAULT '{}'::JSONB,
    appearance_config_json JSONB NOT NULL DEFAULT '{}'::JSONB,
    enabled BOOLEAN NOT NULL DEFAULT FALSE,
    admin_only BOOLEAN NOT NULL DEFAULT FALSE,
    is_deletable BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (guild_id, mode_key)
);

ALTER TABLE modes
    ADD COLUMN IF NOT EXISTS mode_key TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS name TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS description TEXT,
    ADD COLUMN IF NOT EXISTS behavior_type TEXT NOT NULL DEFAULT 'reply',
    ADD COLUMN IF NOT EXISTS duration_seconds INTEGER,
    ADD COLUMN IF NOT EXISTS mode_icon_path TEXT,
    ADD COLUMN IF NOT EXISTS enter_message TEXT,
    ADD COLUMN IF NOT EXISTS exit_message TEXT,
    ADD COLUMN IF NOT EXISTS enter_gif_path TEXT,
    ADD COLUMN IF NOT EXISTS exit_gif_path TEXT,
    ADD COLUMN IF NOT EXISTS enter_notify_channel_id TEXT,
    ADD COLUMN IF NOT EXISTS exit_notify_channel_id TEXT,
    ADD COLUMN IF NOT EXISTS reaction_channel_ids JSONB NOT NULL DEFAULT '[]'::JSONB,
    ADD COLUMN IF NOT EXISTS ignore_channel_ids JSONB NOT NULL DEFAULT '[]'::JSONB,
    ADD COLUMN IF NOT EXISTS cooldown_config_json JSONB NOT NULL DEFAULT '{}'::JSONB,
    ADD COLUMN IF NOT EXISTS appearance_config_json JSONB NOT NULL DEFAULT '{}'::JSONB,
    ADD COLUMN IF NOT EXISTS enabled BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS admin_only BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS is_deletable BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

CREATE UNIQUE INDEX IF NOT EXISTS idx_modes_guild_mode_key_unique
    ON modes(guild_id, mode_key);

CREATE TABLE IF NOT EXISTS mode_reply_choices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id TEXT NOT NULL REFERENCES guilds(guild_id) ON DELETE CASCADE,
    mode_id BIGINT NOT NULL REFERENCES modes(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    body TEXT,
    image_path TEXT,
    appearance_rate INTEGER NOT NULL DEFAULT 1 CHECK (appearance_rate > 0),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK (body IS NOT NULL OR image_path IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS mode_trigger_conditions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id TEXT NOT NULL REFERENCES guilds(guild_id) ON DELETE CASCADE,
    mode_id BIGINT NOT NULL REFERENCES modes(id) ON DELETE CASCADE,
    condition_group_key TEXT NOT NULL DEFAULT 'default',
    group_operator TEXT NOT NULL DEFAULT 'AND' CHECK (group_operator IN ('AND', 'OR')),
    condition_type TEXT NOT NULL CHECK (
        condition_type IN (
            'probability',
            'counter_threshold',
            'period_not_triggered',
            'manual',
            'test',
            'schedule'
        )
    ),
    condition_config_json JSONB NOT NULL DEFAULT '{}'::JSONB,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS mode_exit_conditions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id TEXT NOT NULL REFERENCES guilds(guild_id) ON DELETE CASCADE,
    mode_id BIGINT NOT NULL REFERENCES modes(id) ON DELETE CASCADE,
    condition_type TEXT NOT NULL CHECK (condition_type IN ('duration_elapsed', 'manual')),
    condition_config_json JSONB NOT NULL DEFAULT '{}'::JSONB,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS mode_states (
    guild_id TEXT PRIMARY KEY REFERENCES guilds(guild_id) ON DELETE CASCADE,
    current_mode_id BIGINT REFERENCES modes(id) ON DELETE SET NULL,
    active_until TIMESTAMPTZ,
    pseudo_offline_until TIMESTAMPTZ,
    shikocchi_count INTEGER NOT NULL DEFAULT 0 CHECK (shikocchi_count >= 0),
    period_states_json JSONB NOT NULL DEFAULT '{}'::JSONB,
    state_json JSONB NOT NULL DEFAULT '{}'::JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_counters_guild_id
    ON counters(guild_id);

CREATE INDEX IF NOT EXISTS idx_counter_states_counter_id
    ON counter_states(counter_id);

CREATE INDEX IF NOT EXISTS idx_modes_guild_id
    ON modes(guild_id);

CREATE INDEX IF NOT EXISTS idx_mode_reply_choices_mode_id
    ON mode_reply_choices(mode_id);

CREATE INDEX IF NOT EXISTS idx_mode_trigger_conditions_mode_id
    ON mode_trigger_conditions(mode_id);

CREATE INDEX IF NOT EXISTS idx_mode_exit_conditions_mode_id
    ON mode_exit_conditions(mode_id);
