CREATE TABLE IF NOT EXISTS mention_reactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id TEXT NOT NULL REFERENCES guilds(guild_id) ON DELETE CASCADE,
    reaction_key TEXT NOT NULL,
    keyword TEXT NOT NULL,
    match_type TEXT NOT NULL DEFAULT 'contains',
    reaction_kind TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    admin_only BOOLEAN NOT NULL DEFAULT FALSE,
    is_system BOOLEAN NOT NULL DEFAULT FALSE,
    is_deletable BOOLEAN NOT NULL DEFAULT TRUE,
    config_json JSONB NOT NULL DEFAULT '{}'::JSONB,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (guild_id, reaction_key),
    UNIQUE (guild_id, keyword)
);

ALTER TABLE mention_reactions
    ADD COLUMN IF NOT EXISTS reaction_key TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS keyword TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS match_type TEXT NOT NULL DEFAULT 'contains',
    ADD COLUMN IF NOT EXISTS reaction_kind TEXT NOT NULL DEFAULT 'random',
    ADD COLUMN IF NOT EXISTS name TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS description TEXT,
    ADD COLUMN IF NOT EXISTS admin_only BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS is_system BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS is_deletable BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS config_json JSONB NOT NULL DEFAULT '{}'::JSONB,
    ADD COLUMN IF NOT EXISTS enabled BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS sort_order INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

DO $$
BEGIN
    IF to_regclass('public.mention_reactions') IS NOT NULL THEN
        ALTER TABLE mention_reactions
            DROP CONSTRAINT IF EXISTS mention_reactions_match_type_check;
        ALTER TABLE mention_reactions
            ADD CONSTRAINT mention_reactions_match_type_check
            CHECK (match_type IN ('contains', 'exact', 'prefix', 'regex'));

        ALTER TABLE mention_reactions
            DROP CONSTRAINT IF EXISTS mention_reactions_reaction_kind_check;
        ALTER TABLE mention_reactions
            ADD CONSTRAINT mention_reactions_reaction_kind_check
            CHECK (reaction_kind IN ('random', 'search'));
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS mention_reaction_choices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id TEXT NOT NULL REFERENCES guilds(guild_id) ON DELETE CASCADE,
    mention_reaction_id BIGINT NOT NULL REFERENCES mention_reactions(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    body TEXT,
    image_path TEXT,
    appearance_rate INTEGER NOT NULL DEFAULT 1 CHECK (appearance_rate > 0),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK (body IS NOT NULL OR image_path IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS mention_search_handlers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id TEXT NOT NULL REFERENCES guilds(guild_id) ON DELETE CASCADE,
    mention_reaction_id BIGINT NOT NULL REFERENCES mention_reactions(id) ON DELETE CASCADE,
    handler_key TEXT NOT NULL,
    settings_json JSONB NOT NULL DEFAULT '{}'::JSONB,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (guild_id, handler_key),
    UNIQUE (mention_reaction_id)
);

CREATE INDEX IF NOT EXISTS idx_mention_reactions_guild_id_enabled
    ON mention_reactions(guild_id, enabled);

CREATE INDEX IF NOT EXISTS idx_mention_reactions_keyword_length
    ON mention_reactions(guild_id, LENGTH(keyword) DESC, created_at ASC);

CREATE INDEX IF NOT EXISTS idx_mention_reaction_choices_reaction_id
    ON mention_reaction_choices(mention_reaction_id);

CREATE INDEX IF NOT EXISTS idx_mention_search_handlers_reaction_id
    ON mention_search_handlers(mention_reaction_id);
