CREATE TABLE IF NOT EXISTS special_effect_tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id TEXT NOT NULL REFERENCES guilds(guild_id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    description TEXT,
    color TEXT NOT NULL DEFAULT '#6B7280',
    admin_only BOOLEAN NOT NULL DEFAULT FALSE,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    is_deletable BOOLEAN NOT NULL DEFAULT TRUE,
    priority INTEGER NOT NULL DEFAULT 0,
    target_type TEXT NOT NULL,
    trigger_timing TEXT NOT NULL DEFAULT 'choice_selected',
    effect_type TEXT NOT NULL,
    effect_config_json JSONB NOT NULL DEFAULT '{}'::JSONB,
    additional_text TEXT,
    additional_post_timing TEXT NOT NULL DEFAULT 'none',
    expires_type TEXT NOT NULL DEFAULT 'permanent',
    expires_value INTEGER,
    expires_at TIMESTAMPTZ,
    cooldown_seconds INTEGER,
    cooldown_scope TEXT NOT NULL DEFAULT 'none',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE special_effect_tags
    ADD COLUMN IF NOT EXISTS description TEXT,
    ADD COLUMN IF NOT EXISTS color TEXT NOT NULL DEFAULT '#6B7280',
    ADD COLUMN IF NOT EXISTS admin_only BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS enabled BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS is_deletable BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS priority INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS target_type TEXT NOT NULL DEFAULT 'mention_reaction_choice',
    ADD COLUMN IF NOT EXISTS trigger_timing TEXT NOT NULL DEFAULT 'choice_selected',
    ADD COLUMN IF NOT EXISTS effect_type TEXT NOT NULL DEFAULT 'message',
    ADD COLUMN IF NOT EXISTS effect_config_json JSONB NOT NULL DEFAULT '{}'::JSONB,
    ADD COLUMN IF NOT EXISTS additional_text TEXT,
    ADD COLUMN IF NOT EXISTS additional_post_timing TEXT NOT NULL DEFAULT 'none',
    ADD COLUMN IF NOT EXISTS expires_type TEXT NOT NULL DEFAULT 'permanent',
    ADD COLUMN IF NOT EXISTS expires_value INTEGER,
    ADD COLUMN IF NOT EXISTS expires_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS cooldown_seconds INTEGER,
    ADD COLUMN IF NOT EXISTS cooldown_scope TEXT NOT NULL DEFAULT 'none',
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

CREATE TABLE IF NOT EXISTS special_effect_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id TEXT NOT NULL REFERENCES guilds(guild_id) ON DELETE CASCADE,
    special_effect_tag_id BIGINT NOT NULL REFERENCES special_effect_tags(id) ON DELETE CASCADE,
    target_type TEXT NOT NULL,
    target_id BIGINT NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (special_effect_tag_id, target_type, target_id)
);

CREATE INDEX IF NOT EXISTS idx_special_effect_tags_guild_id
    ON special_effect_tags(guild_id);

CREATE INDEX IF NOT EXISTS idx_special_effect_assignments_target
    ON special_effect_assignments(guild_id, target_type, target_id);
