CREATE TABLE IF NOT EXISTS mention_limited_effects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id TEXT NOT NULL REFERENCES guilds(guild_id) ON DELETE CASCADE,
    discord_user_id TEXT NOT NULL,
    display_name TEXT,
    effect_tag_id BIGINT NOT NULL REFERENCES special_effect_tags(id) ON DELETE CASCADE,
    description TEXT,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (guild_id, discord_user_id, effect_tag_id)
);

CREATE INDEX IF NOT EXISTS idx_mention_limited_effects_guild_user
    ON mention_limited_effects(guild_id, discord_user_id);

CREATE INDEX IF NOT EXISTS idx_mention_limited_effects_tag
    ON mention_limited_effects(effect_tag_id);
