CREATE TABLE IF NOT EXISTS mode_trigger_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id TEXT NOT NULL REFERENCES guilds(guild_id) ON DELETE CASCADE,
    mode_id BIGINT NOT NULL REFERENCES modes(id) ON DELETE CASCADE,
    period_key TEXT NOT NULL,
    triggered_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    metadata_json JSONB NOT NULL DEFAULT '{}'::JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (guild_id, mode_id, period_key)
);

CREATE INDEX IF NOT EXISTS idx_mode_trigger_history_guild_mode
    ON mode_trigger_history (guild_id, mode_id);
