CREATE TABLE IF NOT EXISTS auto_post_delivery_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id TEXT NOT NULL REFERENCES guilds(guild_id) ON DELETE CASCADE,
    auto_post_id BIGINT NOT NULL REFERENCES auto_posts(id) ON DELETE CASCADE,
    due_key TEXT NOT NULL,
    delivered_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    channel_id TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (auto_post_id, due_key)
);

CREATE INDEX IF NOT EXISTS idx_auto_post_delivery_history_guild
    ON auto_post_delivery_history (guild_id, auto_post_id);
