ALTER TABLE special_effect_tags
    DROP CONSTRAINT IF EXISTS special_effect_tags_effect_type_check;

ALTER TABLE special_effect_tags
    ADD CONSTRAINT special_effect_tags_effect_type_check
    CHECK (
        effect_type IN (
            'probability_multiplier',
            'next_action_count_add',
            'count_add',
            'mode_lottery',
            'pseudo_offline_lottery',
            'hankaku',
            'shikocchi_lottery',
            'custom',
            'probability_message',
            'message',
            'reaction',
            'counter_delta',
            'counter_set',
            'next_action_count',
            'mode_roll',
            'mode_enter',
            'temporary_state',
            'ng_behavior',
            'extra_choice',
            'destroy',
            'mention_suffix_guard'
        )
    );

CREATE TABLE IF NOT EXISTS reaction_threshold_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id TEXT NOT NULL REFERENCES guilds(guild_id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    config_json JSONB NOT NULL DEFAULT '{}'::JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_reaction_threshold_rules_guild_enabled
    ON reaction_threshold_rules(guild_id, enabled);

CREATE TABLE IF NOT EXISTS reaction_threshold_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id TEXT NOT NULL REFERENCES guilds(guild_id) ON DELETE CASCADE,
    rule_id BIGINT NOT NULL REFERENCES reaction_threshold_rules(id) ON DELETE CASCADE,
    message_id TEXT NOT NULL,
    channel_id TEXT NOT NULL,
    emoji_key TEXT NOT NULL,
    threshold INTEGER NOT NULL DEFAULT 5,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (guild_id, rule_id, message_id, emoji_key, threshold)
);

CREATE INDEX IF NOT EXISTS idx_reaction_threshold_events_lookup
    ON reaction_threshold_events(guild_id, message_id, emoji_key);
