CREATE TABLE IF NOT EXISTS deck_search_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bot_id TEXT NOT NULL DEFAULT 'ichiyon',
    guild_id TEXT NOT NULL REFERENCES guilds(guild_id) ON DELETE CASCADE,
    fetch_since_date DATE,
    max_lookback_days INTEGER NOT NULL DEFAULT 30 CHECK (max_lookback_days > 0),
    updated_by TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (bot_id, guild_id)
);

CREATE INDEX IF NOT EXISTS idx_deck_search_settings_bot_guild
    ON deck_search_settings(bot_id, guild_id);
