CREATE TABLE IF NOT EXISTS x_update_watches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bot_id TEXT NOT NULL DEFAULT 'ichiyon',
    guild_id TEXT NOT NULL REFERENCES guilds(guild_id) ON DELETE CASCADE,
    channel_id TEXT NOT NULL,
    x_username TEXT NOT NULL,
    x_user_id TEXT,
    display_name TEXT,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    include_replies BOOLEAN NOT NULL DEFAULT FALSE,
    include_reposts BOOLEAN NOT NULL DEFAULT FALSE,
    include_quotes BOOLEAN NOT NULL DEFAULT FALSE,
    check_interval_seconds INTEGER NOT NULL DEFAULT 900 CHECK (check_interval_seconds > 0),
    last_seen_post_id TEXT,
    last_posted_post_id TEXT,
    last_checked_at TIMESTAMPTZ,
    last_success_at TIMESTAMPTZ,
    last_error TEXT,
    post_template TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_x_update_watches_due
    ON x_update_watches (bot_id, enabled, last_checked_at);

CREATE INDEX IF NOT EXISTS idx_x_update_watches_guild
    ON x_update_watches (bot_id, guild_id);

CREATE INDEX IF NOT EXISTS idx_x_update_watches_account
    ON x_update_watches (bot_id, guild_id, channel_id, x_username);

CREATE TABLE IF NOT EXISTS x_update_post_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    watch_id BIGINT NOT NULL REFERENCES x_update_watches(id) ON DELETE CASCADE,
    post_id TEXT NOT NULL,
    post_url TEXT NOT NULL,
    post_text TEXT,
    posted_channel_id TEXT,
    posted_message_id TEXT,
    detected_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    posted_at TIMESTAMPTZ,
    UNIQUE (watch_id, post_id)
);

CREATE INDEX IF NOT EXISTS idx_x_update_post_history_watch
    ON x_update_post_history (watch_id, detected_at DESC);
