CREATE TABLE IF NOT EXISTS bot_instances (
    bot_id TEXT PRIMARY KEY,
    display_name TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    token_env_key TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS bot_permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bot_id TEXT NOT NULL REFERENCES bot_instances(bot_id) ON DELETE CASCADE,
    discord_user_id TEXT NOT NULL,
    guild_id TEXT,
    role TEXT NOT NULL CHECK (role IN ('global_admin', 'guild_admin', 'editor', 'viewer')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (bot_id, discord_user_id, guild_id)
);

INSERT INTO bot_instances (bot_id, display_name, description, enabled, token_env_key)
VALUES
    ('ichiyon', 'いちよんロボ', '既存のいちよんロボ', TRUE, 'ICHIYON_DISCORD_TOKEN'),
    ('irsia', 'イルシア', 'v3.0で追加するBotインスタンス', TRUE, 'IRSIA_DISCORD_TOKEN')
ON CONFLICT (bot_id) DO NOTHING;

ALTER TABLE IF EXISTS feature_flags
    ADD COLUMN IF NOT EXISTS bot_id TEXT NOT NULL DEFAULT 'ichiyon';

ALTER TABLE IF EXISTS mention_reactions
    ADD COLUMN IF NOT EXISTS bot_id TEXT NOT NULL DEFAULT 'ichiyon';

ALTER TABLE IF EXISTS mention_reaction_choices
    ADD COLUMN IF NOT EXISTS bot_id TEXT NOT NULL DEFAULT 'ichiyon';

ALTER TABLE IF EXISTS mention_search_handlers
    ADD COLUMN IF NOT EXISTS bot_id TEXT NOT NULL DEFAULT 'ichiyon';

ALTER TABLE IF EXISTS reactions
    ADD COLUMN IF NOT EXISTS bot_id TEXT NOT NULL DEFAULT 'ichiyon';

ALTER TABLE IF EXISTS ng_words
    ADD COLUMN IF NOT EXISTS bot_id TEXT NOT NULL DEFAULT 'ichiyon';

ALTER TABLE IF EXISTS special_effect_tags
    ADD COLUMN IF NOT EXISTS bot_id TEXT NOT NULL DEFAULT 'ichiyon';

ALTER TABLE IF EXISTS special_effect_assignments
    ADD COLUMN IF NOT EXISTS bot_id TEXT NOT NULL DEFAULT 'ichiyon';

ALTER TABLE IF EXISTS counters
    ADD COLUMN IF NOT EXISTS bot_id TEXT NOT NULL DEFAULT 'ichiyon';

ALTER TABLE IF EXISTS counter_states
    ADD COLUMN IF NOT EXISTS bot_id TEXT NOT NULL DEFAULT 'ichiyon';

ALTER TABLE IF EXISTS modes
    ADD COLUMN IF NOT EXISTS bot_id TEXT NOT NULL DEFAULT 'ichiyon';

ALTER TABLE IF EXISTS mode_reply_choices
    ADD COLUMN IF NOT EXISTS bot_id TEXT NOT NULL DEFAULT 'ichiyon';

ALTER TABLE IF EXISTS mode_trigger_conditions
    ADD COLUMN IF NOT EXISTS bot_id TEXT NOT NULL DEFAULT 'ichiyon';

ALTER TABLE IF EXISTS mode_exit_conditions
    ADD COLUMN IF NOT EXISTS bot_id TEXT NOT NULL DEFAULT 'ichiyon';

ALTER TABLE IF EXISTS mode_states
    ADD COLUMN IF NOT EXISTS bot_id TEXT NOT NULL DEFAULT 'ichiyon';

ALTER TABLE IF EXISTS auto_posts
    ADD COLUMN IF NOT EXISTS bot_id TEXT NOT NULL DEFAULT 'ichiyon';

ALTER TABLE IF EXISTS auto_post_delivery_history
    ADD COLUMN IF NOT EXISTS bot_id TEXT NOT NULL DEFAULT 'ichiyon';

ALTER TABLE IF EXISTS mention_limited_effects
    ADD COLUMN IF NOT EXISTS bot_id TEXT NOT NULL DEFAULT 'ichiyon';

ALTER TABLE IF EXISTS reaction_threshold_rules
    ADD COLUMN IF NOT EXISTS bot_id TEXT NOT NULL DEFAULT 'ichiyon';

ALTER TABLE IF EXISTS reaction_threshold_events
    ADD COLUMN IF NOT EXISTS bot_id TEXT NOT NULL DEFAULT 'ichiyon';

CREATE INDEX IF NOT EXISTS idx_bot_permissions_user
    ON bot_permissions(discord_user_id);

CREATE INDEX IF NOT EXISTS idx_feature_flags_bot_guild
    ON feature_flags(bot_id, guild_id);

CREATE INDEX IF NOT EXISTS idx_mention_reactions_bot_guild_enabled
    ON mention_reactions(bot_id, guild_id, enabled);

CREATE INDEX IF NOT EXISTS idx_reactions_bot_guild_enabled_priority
    ON reactions(bot_id, guild_id, enabled, priority DESC);

CREATE INDEX IF NOT EXISTS idx_ng_words_bot_guild
    ON ng_words(bot_id, guild_id);

CREATE INDEX IF NOT EXISTS idx_special_effect_tags_bot_guild
    ON special_effect_tags(bot_id, guild_id);

CREATE INDEX IF NOT EXISTS idx_modes_bot_guild_enabled
    ON modes(bot_id, guild_id, enabled);

CREATE INDEX IF NOT EXISTS idx_auto_posts_bot_guild_enabled
    ON auto_posts(bot_id, guild_id, enabled);

CREATE INDEX IF NOT EXISTS idx_mention_limited_effects_bot_guild_user
    ON mention_limited_effects(bot_id, guild_id, discord_user_id);

CREATE INDEX IF NOT EXISTS idx_reaction_threshold_rules_bot_guild_enabled
    ON reaction_threshold_rules(bot_id, guild_id, enabled);
