CREATE TABLE IF NOT EXISTS bot_tts_settings (
    bot_id TEXT NOT NULL,
    guild_id TEXT NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    auto_join_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    speaker_id INTEGER,
    speaker_name TEXT NOT NULL DEFAULT '',
    tts_volume_percent INTEGER NOT NULL DEFAULT 50,
    speed_scale NUMERIC(4, 2) NOT NULL DEFAULT 1.00,
    user_pitch_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    pitch_variation NUMERIC(4, 2) NOT NULL DEFAULT 0.06,
    max_text_length INTEGER NOT NULL DEFAULT 300,
    queue_limit INTEGER NOT NULL DEFAULT 50,
    ducking_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    ducking_music_gain NUMERIC(4, 2) NOT NULL DEFAULT 0.50,
    ducking_attack_ms INTEGER NOT NULL DEFAULT 100,
    ducking_release_ms INTEGER NOT NULL DEFAULT 300,
    credit_text TEXT NOT NULL DEFAULT 'VOICEVOX: 選択した話者',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (bot_id, guild_id),
    CHECK (tts_volume_percent >= 0 AND tts_volume_percent <= 100),
    CHECK (speed_scale >= 0.50 AND speed_scale <= 2.00),
    CHECK (pitch_variation >= 0.00 AND pitch_variation <= 0.20),
    CHECK (max_text_length >= 1 AND max_text_length <= 1000),
    CHECK (queue_limit >= 1 AND queue_limit <= 200),
    CHECK (ducking_music_gain >= 0.00 AND ducking_music_gain <= 1.00),
    CHECK (ducking_attack_ms >= 0 AND ducking_attack_ms <= 5000),
    CHECK (ducking_release_ms >= 0 AND ducking_release_ms <= 5000)
);

