CREATE TABLE IF NOT EXISTS mezamashi_horoscope_cache (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_date DATE NOT NULL UNIQUE,
    payload_json JSONB NOT NULL,
    source_url TEXT NOT NULL,
    fetched_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_mezamashi_horoscope_cache_fetched_at
    ON mezamashi_horoscope_cache(fetched_at DESC);

CREATE TABLE IF NOT EXISTS mezamashi_horoscope_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bot_id TEXT NOT NULL DEFAULT 'ichiyon',
    guild_id TEXT NOT NULL REFERENCES guilds(guild_id) ON DELETE CASCADE,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    ranking_command_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    zodiac_command_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    auto_post_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    auto_post_channel_id TEXT,
    auto_post_time TEXT NOT NULL DEFAULT '07:10',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (bot_id, guild_id),
    CHECK (auto_post_time ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$')
);

CREATE INDEX IF NOT EXISTS idx_mezamashi_horoscope_settings_guild
    ON mezamashi_horoscope_settings(bot_id, guild_id);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'chk_mezamashi_horoscope_settings_auto_post_time'
    ) THEN
        ALTER TABLE mezamashi_horoscope_settings
            ADD CONSTRAINT chk_mezamashi_horoscope_settings_auto_post_time
            CHECK (auto_post_time ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$');
    END IF;
END $$;
