// Generated by build_minecraft_cosmetics.py; IDs are permanent.
export const catalog = {
  "accessories": [],
  "digest": "ce1cf3f31ed38b2a89f5ad42f25f65b22bd446b2b2dc8840b5b6ebe1a840b9bb",
  "skins": [
    {
      "digest": "d44337eafa2c886fd5f19288dee656fc226d7d17cca8873528005a908365d047",
      "id": 1,
      "key": "kiana",
      "kind": "skin",
      "model": "classic",
      "name": "キアナ"
    },
    {
      "digest": "582ee623bd2873f17a6ce0452d66b4c9dd7decfe0640c7d6abb05fe181503265",
      "id": 2,
      "key": "mei",
      "kind": "skin",
      "model": "classic",
      "name": "芽衣"
    },
    {
      "digest": "5026fb9cab6728a73c5b6a813ba47a9108cf9101de80d50782d45eaac373cd33",
      "id": 3,
      "key": "bronya",
      "kind": "skin",
      "model": "classic",
      "name": "ブローニャ"
    },
    {
      "digest": "073d8d841495ec960feba00caa116a7e826a30cfd4f318ce09ff81bf310a86c2",
      "id": 4,
      "key": "albert",
      "kind": "skin",
      "model": "classic",
      "name": "アルベール"
    }
  ]
};
