"""Focused asset checks; no server, deployment or full source regeneration."""
import argparse
import hashlib
import json
import math
from pathlib import Path
import subprocess
import tempfile
import unittest

from PIL import Image, ImageChops

from build_minecraft_video import BIG_PROFILES, ROOT, SMALL, build, make_atlases, probe, run, write_definitions

RP = ROOT / "minecraft/resource_packs/ichiyon_video_big_rp"
BP = ROOT / "minecraft/behavior_packs/ichiyon_avatar_bp"
REPORT_DIR = ROOT / "minecraft/video_screen_big"
SCRIPTS = ROOT / "minecraft/behavior_packs/import_structures/scripts"
SOURCE = None


def read(path):
    return json.loads(path.read_text(encoding="utf-8"))


class BigVideoChecks(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.report = read(REPORT_DIR / "build_report.json")
        cls.output = cls.report["output"]
        cls.profile = BIG_PROFILES[cls.output["profile"]]

    def test_source_and_20fps_contract(self):
        source, output = self.report["source"], self.output
        self.assertEqual((source["width"], source["height"], source["fps"], source["frameCount"]),
                         (640, 360, "24/1", 12244))
        self.assertEqual(source["bytes"], 24332100)
        self.assertEqual(source["audio"], {"codec": "aac", "channels": 2, "sampleRate": 44100})
        self.assertEqual((output["frameWidth"], output["frameHeight"], output["fps"]), (128, 72, 20))
        self.assertEqual(output["duration"], output["frameCount"] / 20)
        self.assertLess(abs(output["duration"] - source["videoDuration"]), 1 / 20)
        self.assertEqual(output["sound"], "ichiyon.video_screen_big.audio")

    def test_generated_javascript(self):
        script = (SCRIPTS / "video_big_media.generated.js").read_text(encoding="utf-8")
        prefix = "// Generated by scripts/build_minecraft_video.py. Do not edit.\nexport const VIDEO_BIG_MEDIA = "
        self.assertTrue(script.startswith(prefix))
        self.assertTrue(script.endswith(";\n"))
        media = json.loads(script[len(prefix):-2])
        self.assertEqual(media, {key: self.output[key] for key in ("fps", "frameCount", "duration", "sound")})
        subprocess.run(["node", "--input-type=module", "--check"], input=script.encode(), check=True,
                       capture_output=True)

    def test_only_synchronized_frame_property(self):
        entity = read(BP / "entities/video_screen_big.json")["minecraft:entity"]
        self.assertEqual(entity["description"]["identifier"], "ichiyon:video_screen_big")
        self.assertEqual(entity["description"]["properties"], {"ichiyon:frame": {
            "type": "int", "range": [-1, self.output["frameCount"] - 1], "default": -1, "client_sync": True}})
        components = entity["components"]
        self.assertEqual(components["minecraft:type_family"]["family"], ["ichiyon_video_screen_big"])
        self.assertEqual(components["minecraft:collision_box"], {"width": 0, "height": 0})
        self.assertEqual(components["minecraft:physics"], {"has_gravity": False, "has_collision": False})
        self.assertIn("minecraft:persistent", components)

    def test_geometry_facing_planes_and_bounds(self):
        geometries = read(RP / "models/entity/video_screen_big.geo.json")["minecraft:geometry"]
        self.assertEqual(len(geometries), 2)
        video, black = [g["bones"][0]["cubes"][0] for g in geometries]
        self.assertEqual(video["size"], [176 * 16 / 9, 176, 0])
        self.assertEqual(black["size"], [384, 176, 0])
        for cube, z in [(video, -0.5), (black, 0)]:
            self.assertEqual(cube["origin"], [-cube["size"][0] / 2, 0, z])
            self.assertEqual(set(cube["uv"]), {"north"})
        self.assertGreater(-video["origin"][2], -black["origin"][2])
        self.assertAlmostEqual((black["size"][0] - video["size"][0]) / 32, 2.2222222222222223)
        for geometry in geometries:
            desc = geometry["description"]
            self.assertEqual((desc["visible_bounds_width"], desc["visible_bounds_height"]), (26, 13))
            self.assertEqual(desc["visible_bounds_offset"], [0, 5.5, 0])

    def test_standard_uv_render_and_private_material(self):
        p = self.profile
        client = read(RP / "entity/video_screen_big.entity.json")["minecraft:client_entity"]["description"]
        self.assertEqual(client["identifier"], "ichiyon:video_screen_big")
        self.assertNotIn("scripts", client)
        self.assertEqual(client["materials"], {"default": "ichiyon_video_big_uv", "black": "entity_alphatest"})
        self.assertEqual(client["render_controllers"], ["controller.render.ichiyon_video_big_black",
            {"controller.render.ichiyon_video_screen_big": "q.property('ichiyon:frame') >= 0"}])
        material = read(RP / "materials/entity.material")["materials"]
        self.assertEqual(material, {"version": "1.0.0",
            "ichiyon_video_big_uv:entity_alphatest": {"+defines": ["USE_UV_ANIM"]}})
        controllers = read(RP / "render_controllers/video_screen_big.render_controllers.json")["render_controllers"]
        black = controllers["controller.render.ichiyon_video_big_black"]
        self.assertEqual(black["textures"], ["Texture.black"])
        self.assertTrue(black["ignore_lighting"])
        render = controllers["controller.render.ichiyon_video_screen_big"]
        self.assertEqual(render["geometry"], "Geometry.default")
        self.assertEqual(render["materials"], [{"*": "Material.default"}])
        self.assertTrue(render["ignore_lighting"])
        frame = "math.max(0, q.property('ichiyon:frame'))"
        self.assertEqual(render["textures"], [f"Array.frames[math.floor({frame} / {p.capacity})]"])
        self.assertEqual(render["uv_anim"], {
            "offset": [f"(math.mod({frame}, {p.cols}) * {p.cell_width} + 1) / {p.atlas_width}",
                f"(math.floor(math.mod({frame}, {p.capacity}) / {p.cols}) * {p.cell_height} + 1) / {p.atlas_height}"],
            "scale": [p.width / p.atlas_width, p.height / p.atlas_height]})
        self.assertEqual(render["arrays"]["textures"]["Array.frames"],
                         [f"Texture.atlas_{i}" for i in range(self.output["atlasCount"])])
        self.assertEqual(len(client["textures"]), self.output["atlasCount"] + 1)
        for name, texture in client["textures"].items():
            self.assertTrue(texture.startswith("textures/entity/video_screen_big/"), name)
            self.assertTrue((RP / (texture + ".png")).is_file(), texture)

    def test_atlas_count_dimensions_padding_and_frame_boundaries(self):
        p, output = self.profile, self.output
        textures = RP / "textures/entity/video_screen_big"
        self.assertEqual(output["atlasCount"], math.ceil(output["frameCount"] / p.capacity))
        self.assertEqual(sorted(f.name for f in textures.glob("*.png")),
                         [f"atlas_{i:03d}.png" for i in range(output["atlasCount"])] + ["black.png"])
        hashes = set()
        for index in range(output["atlasCount"]):
            with Image.open(textures / f"atlas_{index:03d}.png") as atlas:
                self.assertEqual(atlas.size, (p.atlas_width, p.atlas_height))
                self.assertLessEqual(max(atlas.size), 2048)
                self.assertEqual(atlas.mode, "RGB")
                used = min(p.capacity, output["frameCount"] - index * p.capacity)
                for slot in range(used):
                    x, y = slot % p.cols * p.cell_width, slot // p.cols * p.cell_height
                    cell = atlas.crop((x, y, x + p.cell_width, y + p.cell_height))
                    pairs = [((0, 1, 1, p.height + 1), (1, 1, 2, p.height + 1)),
                             ((p.width + 1, 1, p.width + 2, p.height + 1), (p.width, 1, p.width + 1, p.height + 1)),
                             ((1, 0, p.width + 1, 1), (1, 1, p.width + 1, 2)),
                             ((1, p.height + 1, p.width + 1, p.height + 2), (1, p.height, p.width + 1, p.height + 1))]
                    for border, adjacent in pairs:
                        self.assertIsNone(ImageChops.difference(cell.crop(border), cell.crop(adjacent)).getbbox(),
                                          f"atlas {index}, slot {slot}, border {border}")
                    for corner, adjacent in [((0, 0), (1, 1)), ((p.width + 1, 0), (p.width, 1)),
                                             ((0, p.height + 1), (1, p.height)),
                                             ((p.width + 1, p.height + 1), (p.width, p.height))]:
                        self.assertEqual(cell.getpixel(corner), cell.getpixel(adjacent))
                    if slot in {0, used // 2, used - 1}:
                        hashes.add(hashlib.sha256(cell.tobytes()).hexdigest())
                for slot in range(used, p.capacity):
                    x, y = slot % p.cols * p.cell_width, slot // p.cols * p.cell_height
                    self.assertIsNone(atlas.crop((x, y, x + p.cell_width, y + p.cell_height)).getbbox())
        self.assertGreater(len(hashes), 20)
        with Image.open(textures / "black.png") as black:
            self.assertEqual(black.size, (1, 1))
            self.assertEqual(black.getpixel((0, 0)), (0, 0, 0))

    def test_sound_registration_and_streaming_audio(self):
        fragment = read(REPORT_DIR / "sound_definitions.fragment.json")
        self.assertEqual(fragment, {"ichiyon.video_screen_big.audio": {
            "category": "record", "min_distance": 32, "max_distance": 64,
            "sounds": [{"name": "sounds/video_screen_big/audio", "stream": True, "is3D": True}]}})
        self.assertEqual(read(RP / "sounds/sound_definitions.json"),
                         {"format_version": "1.20.20", "sound_definitions": fragment})
        audio = probe(RP / "sounds/video_screen_big/audio.ogg")
        self.assertEqual(len(audio["streams"]), 1)
        stream = audio["streams"][0]
        self.assertEqual((stream["codec_name"], stream["channels"], int(stream["sample_rate"])), ("vorbis", 1, 44100))
        self.assertAlmostEqual(float(audio["format"]["duration"]), self.output["duration"], places=3)

    def test_report_sizes_and_memory(self):
        p, out = self.profile, self.output
        textures = RP / "textures/entity/video_screen_big"
        png_bytes = sum(f.stat().st_size for f in textures.glob("atlas_*.png"))
        audio_bytes = (RP / "sounds/video_screen_big/audio.ogg").stat().st_size
        self.assertEqual(out["atlasPngBytes"], png_bytes)
        self.assertEqual(out["audioBytes"], audio_bytes)
        self.assertEqual(out["assetBytes"], png_bytes + audio_bytes + (textures / "black.png").stat().st_size)
        self.assertLess(out["assetBytes"], 100 * 1024 * 1024)
        rgba = out["atlasCount"] * p.atlas_width * p.atlas_height * 4
        self.assertEqual(out["decodedRgbaBytes"], rgba)
        self.assertEqual(out["decodedRgbaWithMipmapsBytes"], math.ceil(rgba * 4 / 3))
        self.assertEqual(out["decodedRgbaPerAtlasBytes"], p.atlas_width * p.atlas_height * 4)
        # Git normalizes JSON/material newlines; the report records build-host bytes.
        lf_bytes, crlf_bytes = 0, 0
        for path in RP.rglob("*"):
            if not path.is_file() or path.name == "manifest.json":
                continue
            data = path.read_bytes()
            if path.suffix in {".json", ".material"}:
                data = data.replace(b"\r\n", b"\n")
                crlf_bytes += len(data.replace(b"\n", b"\r\n"))
            else:
                crlf_bytes += len(data)
            lf_bytes += len(data)
        self.assertIn(out["generatedPackBytesExcludingManifest"], {lf_bytes, crlf_bytes})

    def test_json_and_material_parse(self):
        paths = list(RP.rglob("*.json")) + list(RP.rglob("*.material"))
        paths += list(REPORT_DIR.glob("*.json")) + [BP / "entities/video_screen_big.json"]
        for path in paths:
            self.assertIsInstance(read(path), dict, str(path))

    def test_distributed_estimates(self):
        report = read(REPORT_DIR / "profile_estimates.json")
        self.assertEqual(len(report["sampleStartsSeconds"]), 8)
        self.assertEqual(report["sampleSecondsPerWindow"], 3)
        self.assertEqual([p["profile"] for p in report["profiles"]], list(BIG_PROFILES))
        for estimate in report["profiles"]:
            self.assertEqual(estimate["sampleFrames"], 480)
            self.assertEqual(estimate["fps"], 20)
            self.assertLessEqual(max(estimate["atlasWidth"], estimate["atlasHeight"]), 2048)

    def test_big_definitions_are_reproducible_and_manifest_is_not_owned(self):
        media = {key: self.output[key] for key in ("fps", "frameCount", "duration", "sound")}
        with tempfile.TemporaryDirectory(prefix="big-video-definitions-") as temporary:
            root = Path(temporary)
            write_definitions(root, media, self.output["atlasCount"], self.profile)
            for path in root.rglob("*"):
                if path.is_file():
                    self.assertEqual(path.read_bytes(), (ROOT / path.relative_to(root)).read_bytes(), str(path))
            self.assertFalse(list(root.rglob("manifest.json")))
            self.assertFalse((root / "minecraft/resource_packs/ichiyon_avatar_rp").exists())

    def test_small_definition_output_is_unchanged(self):
        out = read(ROOT / "minecraft/video_screen/build_report.json")["output"]
        media = {key: out[key] for key in ("fps", "frameCount", "duration", "sound")}
        with tempfile.TemporaryDirectory(prefix="small-video-regression-") as temporary:
            root = Path(temporary)
            write_definitions(root, media, out["atlasCount"])
            for path in root.rglob("*"):
                if path.is_file():
                    self.assertEqual(path.read_bytes(), (ROOT / path.relative_to(root)).read_bytes(), str(path))
        self.assertEqual((SMALL.width, SMALL.height, SMALL.fps, SMALL.cols, SMALL.rows), (64, 36, 20, 10, 10))

    def test_short_fixture_crosses_atlas_boundary_and_prunes_only_owned_files(self):
        with tempfile.TemporaryDirectory(prefix="big-video-fixture-") as temporary:
            temp = Path(temporary)
            source = temp / "fixture.mp4"
            root = temp / "output"
            run(["ffmpeg", "-v", "error", "-f", "lavfi", "-i", "testsrc2=size=128x72:rate=24:duration=20.4",
                 "-c:v", "mpeg4", str(source)])
            report = build(source, root, self.profile)
            self.assertEqual(report["output"]["atlasCount"], 2)
            self.assertEqual(report["output"]["frameCount"], 408)
            self.assertIsNone(report["output"]["sound"])
            generated_rp = root / "minecraft/resource_packs/ichiyon_video_big_rp"
            self.assertEqual(read(generated_rp / "sounds/sound_definitions.json")["sound_definitions"], {})
            self.assertFalse(list(root.rglob("manifest.json")))
            textures = generated_rp / "textures/entity/video_screen_big"
            # The final three frames occupy the first three cells in atlas 1.
            raw = run(["ffmpeg", "-v", "error", "-i", str(source), "-vf", "fps=20",
                       "-pix_fmt", "rgb24", "-f", "rawvideo", "-"])
            p = self.profile
            frame_bytes = p.width * p.height * 3
            with Image.open(textures / "atlas_001.png") as atlas:
                for slot in range(3):
                    x = slot * p.cell_width + 1
                    self.assertEqual(atlas.crop((x, 1, x + p.width, 1 + p.height)).tobytes(),
                                     raw[(405 + slot) * frame_bytes:(406 + slot) * frame_bytes])
            first = temp / "first.png"
            Image.frombytes("RGB", (p.width, p.height), raw[:frame_bytes]).save(first)
            # An unrelated PNG must survive atlas cleanup.
            unrelated = textures / "keep.png"
            Image.new("RGB", (1, 1), "red").save(unrelated)
            make_atlases([first], textures, p)
            self.assertFalse((textures / "atlas_001.png").exists())
            self.assertTrue(unrelated.exists())

    def test_optional_original_metadata_and_hash(self):
        if SOURCE is None:
            self.skipTest("Pass --source to check the external original without regenerating it")
        self.assertFalse(SOURCE.resolve().is_relative_to(ROOT))
        self.assertEqual(hashlib.sha256(SOURCE.read_bytes()).hexdigest(), self.report["source"]["sha256"])
        source = probe(SOURCE)
        video = next(s for s in source["streams"] if s["codec_type"] == "video")
        self.assertEqual(int(video["nb_frames"]), self.report["source"]["frameCount"])
        self.assertEqual(video["avg_frame_rate"], self.report["source"]["fps"])


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path)
    args, remainder = parser.parse_known_args()
    SOURCE = args.source
    unittest.main(argv=[__file__, *remainder])
