"""Deterministic pack compiler. Asset names and paths never come from filenames."""
from copy import deepcopy
from io import BytesIO
import json
from zipfile import ZipFile, ZIP_DEFLATED, ZipInfo

from PIL import Image

from bot.services.minecraft_cosmetics import (
    MOLCARS, SLOTS, MAX_ID, asset, json_bytes, public_asset,
)

BP = "behavior_packs/ichiyon_avatar_bp/"
RP = "resource_packs/ichiyon_avatar_rp/"
BRIDGE = "behavior_packs/import_structures/"
PACKS = (BP, RP, BRIDGE)
BUILTINS = (("kiana", "キアナ"), ("mei", "芽衣"), ("bronya", "ブローニャ"), ("albert", "アルベール"))
_DELETED_SKIN_TEXTURE = None
ACCESSORY_GROUPS = {slot: f"ichiyon:itemGroup.molcar_{slot}" for slot in SLOTS}
ACCESSORY_GROUP_LABELS = {
    "ja_JP": {"hat": "モルカー：頭", "face": "モルカー：顔", "neck": "モルカー：首", "back": "モルカー：背中"},
    "en_US": {"hat": "Molcar: Head", "face": "Molcar: Face", "neck": "Molcar: Neck", "back": "Molcar: Back"},
}


def _creative_accessory_catalog(existing, accessories):
    """Refresh our collapsible groups while retaining other catalog entries."""
    catalog = deepcopy(existing) if existing is not None else {
        "format_version": "1.21.60", "minecraft:crafting_items_catalog": {"categories": []}}
    categories = catalog["minecraft:crafting_items_catalog"]["categories"]
    owned_names = set(ACCESSORY_GROUPS.values())
    for category in categories:
        category["groups"] = [group for group in category["groups"]
                              if group.get("group_identifier", {}).get("name") not in owned_names]
    groups = []
    for slot in SLOTS:
        items = [f"ichiyon:accessory_{a['id']}" for a in sorted(accessories, key=lambda a: a["id"]) if a["slot"] == slot]
        if items:
            groups.append({"group_identifier": {"name": ACCESSORY_GROUPS[slot], "icon": items[0]}, "items": items})
    if groups:
        equipment = next((c for c in categories if c["category_name"] == "equipment"), None)
        if equipment is None:
            equipment = {"category_name": "equipment", "groups": []}
            categories.append(equipment)
        equipment["groups"].extend(groups)
    categories[:] = [category for category in categories if category["groups"]]
    return catalog


def builtin_assets(root):
    return [asset("skin", i + 1, key, name, (root / RP / f"textures/entity/avatar/{key}.png").read_bytes())
            for i, (key, name) in enumerate(BUILTINS)]


def deleted_skin_texture():
    global _DELETED_SKIN_TEXTURE
    if _DELETED_SKIN_TEXTURE is None:
        output = BytesIO()
        Image.new("RGBA", (64, 64), (0, 0, 0, 0)).save(output, format="PNG")
        _DELETED_SKIN_TEXTURE = output.getvalue()
    return _DELETED_SKIN_TEXTURE


def catalog_digest(records):
    import hashlib
    return hashlib.sha256(json_bytes([public_asset(a) for a in sorted(records, key=lambda a: (a["kind"], a["id"]))])).hexdigest()


def _model_pair(model, prefix):
    classic = deepcopy(model)
    classic["description"].update(identifier=prefix + ".classic", texture_width=64, texture_height=64)
    slim = deepcopy(classic)
    slim["description"]["identifier"] = prefix + ".slim"
    for bone in slim["bones"]:
        if bone["name"] in ("leftArm", "leftSleeve", "rightArm", "rightSleeve"):
            for cube in bone.get("cubes", []):
                cube["size"][0] = 3
                if bone["name"].startswith("right"):
                    cube["origin"][0] += 1
    return {"format_version": "1.21.0", "minecraft:geometry": [classic, slim]}


def compile_files(root, records, *, revision=None):
    """Return changed/generated files; root is the trusted repository minecraft/ path."""
    records = sorted(records, key=lambda a: (a["kind"], a["id"]))
    for kind in ("skin", "accessory"):
        entries = [r for r in records if r["kind"] == kind]
        if len(entries) > MAX_ID or len({r["id"] for r in entries}) != len(entries) or len({r["key"] for r in entries}) != len(entries):
            raise ValueError("素材IDまたは名前キーが重複しています。")
    for record in records:
        if asset(record["kind"], record["id"], record["key"], record["name"], record["texture"], **{k: record[k] for k in ("model", "slot", "geometry", "icon") if k in record}) != record:
            raise ValueError("未検証の素材です。")
    skins = {a["id"]: a for a in records if a["kind"] == "skin"}
    files = {}
    files[RP + "COPYING-Mojang.txt"] = (root / "cosmetics/vendor/LICENSE.md").read_bytes().replace(b"\r\n", b"\n")

    def read(path):
        return json.loads((root / path).read_text(encoding="utf-8-sig"))

    def put(path, value):
        files[path] = json_bytes(value)

    registry = {"digest": catalog_digest(records), "skins": [public_asset(a) for a in records if a["kind"] == "skin"],
                "accessories": [public_asset(a) | {"item": f"ichiyon:accessory_{a['id']}"} for a in records if a["kind"] == "accessory"]}
    files[BRIDGE + "scripts/cosmetics_catalog.js"] = b"// Generated by build_minecraft_cosmetics.py; IDs are permanent.\nexport const catalog = " + json_bytes(registry).rstrip() + b";\n"
    put("cosmetics/catalog.lock.json", registry)

    avatar = read(BP + "entities/avatar.json")
    entity = avatar["minecraft:entity"]
    entity["components"]["minecraft:interact"] = {"interactions": [{"interact_text": "action.interact.ichiyon_cosmetic_wardrobe", "use_item": False, "swing": False}]}
    groups = entity["component_groups"]
    for key in list(groups):
        if key.startswith("ichiyon:cosmetic_"):
            del groups[key]
    for key in list(entity["events"]):
        if key.startswith("ichiyon:cosmetic_"):
            del entity["events"][key]
    for skin_id in skins:
        groups[f"ichiyon:cosmetic_{skin_id}"] = {"minecraft:variant": {"value": skin_id - 1}}
    variants = sorted(key for key, value in groups.items() if "minecraft:variant" in value)
    for skin_id in skins:
        entity["events"][f"ichiyon:cosmetic_{skin_id}"] = {"remove": {"component_groups": variants}, "add": {"component_groups": [f"ichiyon:cosmetic_{skin_id}"]}}
    for key, _ in BUILTINS:
        entity["events"][f"ichiyon:{key}"]["remove"]["component_groups"] = variants
    put(BP + "entities/avatar.json", avatar)
    mannequin = read(RP + "entity/avatar.entity.json")
    desc = mannequin["minecraft:client_entity"]["description"]
    desc["textures"] = {key: f"textures/entity/avatar/{key}" for key, _ in BUILTINS}
    desc["textures"]["deleted_skin"] = "textures/entity/cosmetics/deleted_skin"
    desc["geometry"].update(classic="geometry.ichiyon.avatar.classic", slim="geometry.ichiyon.avatar.slim")
    textures, geometries = [], []
    for skin_id in range(1, MAX_ID + 1):
        skin = skins.get(skin_id)
        textures.append(f"Texture.skin_{skin['id']}" if skin else "Texture.deleted_skin")
        geometries.append("Geometry." + skin["model"] if skin else "Geometry.classic")
    for skin in skins.values():
        path = f"textures/entity/cosmetics/skin_{skin['id']}"
        desc["textures"][f"skin_{skin['id']}"] = path
        files[RP + path + ".png"] = skin["texture"]
    files[RP + "textures/entity/cosmetics/deleted_skin.png"] = deleted_skin_texture()
    put(RP + "entity/avatar.entity.json", mannequin)
    put(RP + "render_controllers/avatar.render_controllers.json", {
        "format_version": "1.8.0", "render_controllers": {"controller.render.ichiyon.avatar": {
            "arrays": {"textures": {"Array.skins": textures}, "geometries": {"Array.models": geometries}},
            "geometry": "Array.models[query.variant]", "materials": [{"*": "Material.default"}], "textures": ["Array.skins[query.variant]"]}}})
    put(RP + "models/entity/cosmetics_avatar.geo.json", _model_pair(read(RP + "models/entity/avatar.geo.json")["minecraft:geometry"][0], "geometry.ichiyon.avatar"))

    # Keep vanilla behavior/animations and default skin path for skin_id = 0.
    player = read("cosmetics/vendor/player.behavior.json")
    player["minecraft:entity"]["description"]["properties"] = {"ichiyon:skin_id": {"type": "int", "range": [0, MAX_ID], "default": 0, "client_sync": True}}
    put(BP + "entities/player.json", player)
    client = read("cosmetics/vendor/player.entity.json")
    player_desc = client["minecraft:client_entity"]["description"]
    player_desc["textures"].update({key: value for key, value in desc["textures"].items() if key.startswith("skin_")})
    player_desc["geometry"].update(classic="geometry.ichiyon.player.classic", slim="geometry.ichiyon.player.slim")
    render = read("cosmetics/vendor/player.render_controllers.json")["render_controllers"]
    new_render = {}
    controllers = []
    for condition in player_desc["render_controllers"]:
        key, expression = next(iter(condition.items()))
        controllers.append({key: f"({expression}) && query.property('ichiyon:skin_id') == 0"})
        new_key = key.replace("controller.render.player.", "controller.render.ichiyon.cosmetic_player.")
        controllers.append({new_key: f"({expression}) && query.property('ichiyon:skin_id') > 0"})
        controller = deepcopy(render[key])
        controller["arrays"] = {"textures": {"Array.skins": ["Texture.default"] + textures}, "geometries": {"Array.models": ["Geometry.default"] + geometries}}
        controller["geometry"] = "Array.models[query.property('ichiyon:skin_id')]"
        controller["textures"] = ["Array.skins[query.property('ichiyon:skin_id')]"]
        new_render[new_key] = controller
    player_desc["render_controllers"] = controllers
    put(RP + "entity/player.entity.json", client)
    put(RP + "render_controllers/cosmetics_player.render_controllers.json", {"format_version": "1.8.0", "render_controllers": new_render})
    put(RP + "models/entity/cosmetics_player.geo.json", _model_pair(read("cosmetics/vendor/humanoid.custom.geo.json")["minecraft:geometry"][0], "geometry.ichiyon.player"))

    atlas = read(RP + "textures/item_texture.json")
    atlas["texture_data"] = {k: v for k, v in atlas["texture_data"].items() if not k.startswith("ichiyon:accessory_")}
    atlas["texture_data"]["ichiyon:avatar_selector"] = {"textures": "textures/items/taketumi_spawn_egg"}
    put(BP + "items/avatar_selector.json", {"format_version": "1.26.0", "minecraft:item": {
        "description": {"identifier": "ichiyon:avatar_selector", "menu_category": {"category": "items"}},
        "components": {"minecraft:display_name": {"value": "マネキン共通エッグ"}, "minecraft:icon": "ichiyon:avatar_selector", "minecraft:max_stack_size": 1,
                       "minecraft:interact_button": "マネキンを選ぶ", "minecraft:entity_placer": {"entity": "ichiyon:avatar"}}}})
    # Compatibility entity IDs still transform; only the common egg is advertised.
    for key, _ in BUILTINS:
        proxy = read(BP + f"entities/avatar_{key}_placer.json")
        proxy["minecraft:entity"]["description"]["is_spawnable"] = False
        proxy["minecraft:entity"]["components"]["minecraft:interact"] = deepcopy(entity["components"]["minecraft:interact"])
        put(BP + f"entities/avatar_{key}_placer.json", proxy)
        proxy_client = deepcopy(mannequin)
        proxy_client["minecraft:client_entity"]["description"]["identifier"] = f"ichiyon:avatar_{key}_placer"
        put(RP + f"entity/avatar_{key}_placer.entity.json", proxy_client)

    accessories = [a for a in records if a["kind"] == "accessory"]
    accessory_controllers = {}
    for molcar in MOLCARS:
        behavior_path = BP + f"entities/{molcar}.behavior.json"
        mob = read(behavior_path)
        mob["minecraft:entity"]["description"].setdefault("properties", {}).update({f"ichiyon:{slot}": {"type": "int", "range": [0, MAX_ID], "default": 0, "client_sync": True} for slot in SLOTS})
        interact = mob["minecraft:entity"]["components"].setdefault("minecraft:interact", {"interactions": []})
        current = interact.get("interactions", [])
        if isinstance(current, dict):
            current = [current]
        current = [entry for entry in current if not entry.get("interact_text", "").startswith("action.interact.ichiyon_cosmetic_")]
        current.append({"interact_text": "action.interact.ichiyon_cosmetic_remove", "use_item": False, "swing": False,
                        "on_interact": {"filters": {"all_of": [{"test": "is_sneaking", "subject": "other", "value": True}, {"test": "has_equipment", "subject": "other", "domain": "hand", "value": "minecraft:air"}]}}})
        for accessory in accessories:
            current.append({"interact_text": "action.interact.ichiyon_cosmetic_equip", "use_item": False, "swing": False,
                            "on_interact": {"filters": {"test": "has_equipment", "subject": "other", "domain": "hand", "value": f"ichiyon:accessory_{accessory['id']}"}}})
        interact["interactions"] = current
        put(behavior_path, mob)
        client_path = RP + f"entity/{molcar}.entity.json"
        mob_client = read(client_path)
        mob_desc = mob_client["minecraft:client_entity"]["description"]
        for mapping in ("textures", "geometry"):
            mob_desc[mapping] = {k: v for k, v in mob_desc[mapping].items() if not k.startswith("cosmetic_")}
        mob_desc["render_controllers"] = [c for c in mob_desc["render_controllers"] if not (isinstance(c, dict) and next(iter(c)).startswith("controller.render.ichiyon.accessory_"))]
        skeleton = read(RP + f"models/entity/{molcar}.geo.json")["minecraft:geometry"][0]
        for accessory in accessories:
            tag = f"cosmetic_{accessory['id']}"
            identifier = f"geometry.ichiyon.{molcar}.{tag}"
            overlay = json.loads(accessory["geometry"])["minecraft:geometry"][0]
            overlay["description"]["identifier"] = identifier
            base_bones = [{k: deepcopy(v) for k, v in bone.items() if k not in ("cubes", "locators", "poly_mesh")} for bone in skeleton["bones"]]
            for bone in overlay["bones"]:
                bone["name"] = tag + "_" + bone["name"]
                bone["parent"] = tag + "_" + bone["parent"] if bone.get("parent") else "body"
            overlay["bones"] = base_bones + overlay["bones"]
            put(RP + f"models/entity/cosmetics/{molcar}_{tag}.geo.json", {"format_version": "1.16.0", "minecraft:geometry": [overlay]})
            mob_desc["geometry"][tag] = identifier
            mob_desc["textures"][tag] = f"textures/entity/cosmetics/accessory_{accessory['id']}"
            key = f"controller.render.ichiyon.accessory_{accessory['id']}"
            mob_desc["render_controllers"].append({key: f"query.property('ichiyon:{accessory['slot']}') == {accessory['id']}"})
            accessory_controllers[key] = {"geometry": f"Geometry.{tag}", "materials": [{"*": "Material.default"}], "textures": [f"Texture.{tag}"]}
        put(client_path, mob_client)
    for accessory in accessories:
        item_id = f"ichiyon:accessory_{accessory['id']}"
        files[RP + f"textures/entity/cosmetics/accessory_{accessory['id']}.png"] = accessory["texture"]
        files[RP + f"textures/items/cosmetics/accessory_{accessory['id']}.png"] = accessory["icon"]
        atlas["texture_data"][item_id] = {"textures": f"textures/items/cosmetics/accessory_{accessory['id']}"}
        put(BP + f"items/cosmetics/accessory_{accessory['id']}.json", {"format_version": "1.26.0", "minecraft:item": {
            "description": {"identifier": item_id, "menu_category": {"category": "equipment", "group": ACCESSORY_GROUPS[accessory["slot"]]}},
            "components": {"minecraft:display_name": {"value": accessory["name"]}, "minecraft:icon": item_id, "minecraft:max_stack_size": 1, "minecraft:interact_button": "モルカーに装着"}}})
    put(RP + "textures/item_texture.json", atlas)
    creative_catalog_path = BP + "item_catalog/crafting_item_catalog.json"
    if accessories or (root / creative_catalog_path).exists():
        existing = read(creative_catalog_path) if (root / creative_catalog_path).exists() else None
        put(creative_catalog_path, _creative_accessory_catalog(existing, accessories))
    labels = {"ja_JP": {"wardrobe": "着替える", "remove": "アクセサリーを外す", "equip": "アクセサリーを装着"},
              "en_US": {"wardrobe": "Change outfit", "remove": "Remove accessory", "equip": "Equip accessory"}}
    for locale, translations in labels.items():
        path = RP + f"texts/{locale}.lang"
        lines = [line for line in (root / path).read_text(encoding="utf-8").splitlines()
                 if not line.startswith("action.interact.ichiyon_cosmetic_") and line.partition("=")[0] not in ACCESSORY_GROUPS.values()]
        lines.extend(f"action.interact.ichiyon_cosmetic_{key}={value}" for key, value in translations.items())
        for slot in SLOTS:
            if any(a["slot"] == slot for a in accessories):
                lines.append(f"{ACCESSORY_GROUPS[slot]}={ACCESSORY_GROUP_LABELS[locale][slot]}")
        files[path] = ("\n".join(lines) + "\n").encode("utf-8")
    put(RP + "render_controllers/cosmetics_accessories.render_controllers.json", {"format_version": "1.8.0", "render_controllers": accessory_controllers})
    for pack, patch in ((BP, 31), (RP, 36), (BRIDGE, 29)):
        manifest = read(pack + "manifest.json")
        version = [1, 0, patch] if revision is None else [1, 1, revision]
        manifest["header"]["version"] = version
        for module in manifest["modules"]:
            module["version"] = version
        if pack == BRIDGE and not any(d.get("module_name") == "@minecraft/server-ui" for d in manifest["dependencies"]):
            manifest["dependencies"].append({"module_name": "@minecraft/server-ui", "version": "2.0.0"})
        put(pack + "manifest.json", manifest)
    # Avatar BP has a versioned RP dependency.
    behavior = json.loads(files[BP + "manifest.json"])
    resource = json.loads(files[RP + "manifest.json"])
    for dep in behavior.get("dependencies", []):
        if dep.get("uuid") == resource["header"]["uuid"]:
            dep["version"] = resource["header"]["version"]
    put(BP + "manifest.json", behavior)
    return files


def pack_zip(root, records, revision):
    if type(revision) is not int or not 1 <= revision <= 2147483647:
        raise ValueError("パックの版番号が不正です。")
    files = {str(p.relative_to(root)).replace("\\", "/"): p.read_bytes()
             for pack in PACKS for p in (root / pack).rglob("*") if p.is_file()}
    files.update(compile_files(root, records, revision=revision))
    proof = {"revision": revision, "catalog_digest": catalog_digest(records)}
    files["cosmetics-build.json"] = json_bytes(proof)
    out = BytesIO()
    with ZipFile(out, "w", compression=ZIP_DEFLATED) as archive:
        for name, data in sorted(files.items()):
            info = ZipInfo(name, date_time=(2026, 1, 1, 0, 0, 0))
            info.compress_type = ZIP_DEFLATED
            archive.writestr(info, data)
    return out.getvalue()
